global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "flink"
    metrics_path: /
    static_configs:
      - targets: ["flink-jobmanager:9250", "flink-taskmanager:9250"]

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "mysql-exporter"
    static_configs:
      - targets: ["mysql-exporter:9104"]
